Vagrant.configure("2") do |config|
  # Escolhe a box do Debian 12
  config.vm.box = "generic/debian12"

  # Define hostname
  config.vm.hostname = "debian-webserver"

  # Configurações de rede
  config.vm.network "private_network", ip: "192.168.56.20"

  # Porta 80 http guest encaminhada para 8080 no host
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  # Provisionamento com Ansible
  #config.vm.provision "ansible_local" do |ansible|
  #  ansible.playbook = "C:/Users/Aluno/Desktop/aulas/ansible-demo/playbook.yml"
  #end
end