Vagrant.configure("2") do |config|
  # Escolhe a box do Debian 12
  config.vm.box = "generic/debian12"

  # Define hostname
  config.vm.hostname = "debian-ansible"

  # Configurações de rede
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.synced_folder "C:/Users/Aluno/Desktop/ansible-demo", "/home/vagrant/ansible-demo"

  # Provisionamento com shell script
  config.vm.provision "shell", inline: <<-SHELL
    # Atualiza pacotes
    apt-get update -y

    # Instala dependências do Ansible
    apt-get install -y software-properties-common gnupg2

    # Adiciona o repositório do Ansible (caso não esteja no Debian por padrão)
    apt-get install -y ansible

    # Verifica instalação
    ansible --version
  SHELL
end
